<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['radius_app_description'] = 'RADIUS provides additional authentication mechanisms for the system.';
$lang['radius_app_name'] = 'RADIUS Server';
$lang['radius_client'] = 'Client';
$lang['radius_clients'] = 'Clients';
$lang['radius_nickname'] = 'Nickname';
$lang['radius_nickname_invalid'] = 'Nickname is invalid.';
$lang['radius_radius_server'] = 'RADIUS Server';
