<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['radius_app_description'] = 'Serwer RADIUS dostarcza dodatkowe mechanizmy uwierzytelnienia w systemie.';
$lang['radius_app_name'] = 'Serwer RADIUS';
$lang['radius_client'] = 'Klient';
$lang['radius_clients'] = 'Klienci';
$lang['radius_nickname'] = 'Skrót';
$lang['radius_nickname_invalid'] = 'Podana nazwa skrótowa jest nieprawidłowa.';
$lang['radius_radius_server'] = 'Serwer RADIUS';
